language: r
sudo: false
cache: packages

r_github_packages:
  - jimhester/covr

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes --no-examples'

r:
#  - oldrel
  - release
  - devel

env:
  matrix:
    - CXX_OLEVEL=2 CXX=clang++

before_install:
  - mkdir -p ~/.R/
  - echo "CXX = `R CMD config CXX`" >> ~/.R/Makevars
  - echo "CXXFLAGS = `R CMD config CXXFLAGS` -pedantic -g0" >> ~/.R/Makevars
  - export CLANG_EXTRA_ARG=""
  - if [[ $CXX = "clang++" ]] ;  then export CLANG_EXTRA_ARG=" -Qunused-arguments -fcolor-diagnostics " ; fi
  - sed -i.bak "s/ g++/ ${CXX}${CLANG_EXTRA_ARG}/" ~/.R/Makevars
  - sed -i.bak "s/O[0-3]/O$CXX_OLEVEL/" ~/.R/Makevars

#before_script:
#  - Rscript -e "install.packages('Rcpp'), repos='http://cran.rstudio.com')"


script:
  - |
    travis_wait 40 R CMD build . --no-build-vignettes
    travis_wait 40 R CMD check rstansim*tar.gz --no-build-vignettes

after_failure:
  - cat rstansim.Rcheck/00*

after_success:
  - Rscript -e 'covr::codecov()'
