language: r
cache: packages
r:
#  - oldrel
  - release
  - devel

env:
  global:
    - STAN_BRANCH=master
    - STAN_MATH_BRANCH=master
  matrix:
    - CXX_OLEVEL=2 RCPP_VER=cran CXX=clang++

before_script:
  - Rscript -e "install.packages(c('inline', 'Rcpp', 'coda', 'BH', 'RcppEigen', 'RInside', 'RUnit', 'ggplot2', 'gridExtra', 'knitr', 'rmarkdown'), repos='http://cran.rstudio.com')"
  - git config -f .gitmodules submodule.stan.branch ${STAN_BRANCH}
  - git config -f .gitmodules submodule.StanHeaders/inst/include/mathlib.branch ${STAN_MATH_BRANCH}
  - git submodule update --remote
  - R CMD build StanHeaders/
  - R CMD INSTALL `find StanHeaders*.tar.gz`
  - if [[ $TRAVIS_OS_NAME = 'osx' ]] ; then sudo tlmgr update --self; fi
  - if [[ $TRAVIS_OS_NAME = 'osx' ]] ; then sudo tlmgr install verbatimbox readarray ifnextok multirow fancyvrb url titlesec booktabs; fi
  - if [[ $TRAVIS_OS_NAME != 'osx' ]] ; then tlmgr install verbatimbox readarray ifnextok; fi
  - if [[ $TRAVIS_OS_NAME = "osx" ]] ; then  brew install ccache; brew link ccache; fi
  - echo "CXX = `R CMD config CXX`" >> ./rstan/R_Makevars
  - echo "CXXFLAGS = `R CMD config CXXFLAGS` -pedantic -g0" >> ./rstan/R_Makevars
  - export CLANG_EXTRA_ARG=""
  - if [[ $CXX = "clang++" ]] ;  then export CLANG_EXTRA_ARG=" -Qunused-arguments -fcolor-diagnostics " ; fi
  - if [[ $RCPP_VER = 'github' ]]; then R -q -e "options(repos = getCRANmirrors()[1,'URL']); library(devtools); install_github('Rcpp', 'Rcppcore')"; fi
  - echo ${CXX}
  - echo ${CLANG_EXTRA_ARG}
  - sed -i.bak "s/ g++/ ${CXX}${CLANG_EXTRA_ARG}/" ./rstan/R_Makevars
  - sed -i.bak "s/O[0-3]/O$CXX_OLEVEL/" ./rstan/R_Makevars
  - rm ./rstan/R_Makevars.bak
  - more ./rstan/R_Makevars
  - mkdir -p ~/.R/; cat ./rstan/R_Makevars > ~/.R/Makevars
  - more ~/.R/Makevars

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
